# Generated by Django 6.0.2 on 2026-02-07 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EfektUczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True)),
                ('kategoria', models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejtnoci'), ('K', 'Kompetencje')], max_length=1)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KierunekStudiow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('wydzial', models.CharField(default='Wydzia Informatyki', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_modulu', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('MANDT', 'Obowizkowy'), ('SUPPL', 'Wybieralny')], max_length=10)),
                ('semestr', models.IntegerField()),
                ('wymagane_ects', models.IntegerField(help_text='Ile ECTS student paci za ten modu?')),
                ('kierunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kierunekstudiow')),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ROBOCZY', 'Wersja Robocza'), ('ZATWIERDZONY', 'Zatwierdzony')], default='ROBOCZY', max_length=20)),
                ('nazwa_pl', models.CharField(max_length=255)),
                ('nazwa_en', models.CharField(blank=True, max_length=255)),
                ('kod_przedmiotu', models.CharField(max_length=50)),
                ('ects', models.IntegerField()),
                ('godz_wyklad', models.IntegerField(default=0)),
                ('godz_cwiczenia', models.IntegerField(default=0)),
                ('godz_lab', models.IntegerField(default=0)),
                ('godz_projekt', models.IntegerField(default=0)),
                ('godz_seminarium', models.IntegerField(default=0)),
                ('efekty', models.ManyToManyField(blank=True, related_name='przedmioty', to='core.efektuczenia')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przedmioty', to='core.modul')),
                ('opiekun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przedmioty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SzczegolySylabusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_wstepny', models.TextField(verbose_name='Learning Objectives')),
                ('wymagania_wstepne', models.TextField(verbose_name='Prerequisites')),
                ('efekty_tekstowe', models.TextField(verbose_name='Learning Outcomes (Detailed)')),
                ('metody_nauczania', models.TextField(help_text='np. Lecture using multimedia...', verbose_name='Teaching Tools')),
                ('formy_oceny', models.TextField(help_text='np. Written exam...', verbose_name='Ways of Assessment')),
                ('literatura', models.TextField(verbose_name='Primary Source Materials')),
                ('przedmiot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sylabus', to='core.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='TrescZajec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_tematu', models.IntegerField()),
                ('temat', models.TextField()),
                ('liczba_godzin', models.IntegerField()),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonogram', to='core.przedmiot')),
            ],
        ),
    ]
