# Generated by Django 6.0.2 on 2026-02-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szczegolysylabusa',
            name='efekty_tekstowe',
        ),
        migrations.AddField(
            model_name='kierunekstudiow',
            name='forma',
            field=models.CharField(choices=[('S', 'Stacjonarne'), ('N', 'Niestacjonarne')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='kierunekstudiow',
            name='poziom',
            field=models.CharField(choices=[('1', 'Pierwszy stopie'), ('2', 'Drugi stopie')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='badania_naukowe',
            field=models.BooleanField(default=False, verbose_name='Zwizany z badaniami?'),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='cykl_dydaktyczny',
            field=models.CharField(default='2026/2027', max_length=20),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='godz_egzamin',
            field=models.IntegerField(default=0, verbose_name='Godziny na egzamin'),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='jezyk_wykladowy',
            field=models.CharField(default='Polski', max_length=50),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='badania_publikacje',
            field=models.TextField(blank=True, verbose_name='Badania i publikacje'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='efekty_kompetencje',
            field=models.TextField(default='-', verbose_name='Efekty - Kompetencje'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='efekty_umiejetnosci',
            field=models.TextField(default='-', verbose_name='Efekty - Umiejtnoci'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='efekty_wiedza',
            field=models.TextField(default='-', verbose_name='Efekty - Wiedza'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='inne_informacje',
            field=models.TextField(blank=True, verbose_name='Inne informacje'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='odrabianie_zajec',
            field=models.TextField(default='Konsultacja z prowadzcym...', verbose_name='Sposoby odrabiania nieobecnoci'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_egzamin',
            field=models.IntegerField(default=0, verbose_name='Przygotowanie do egzaminu'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_literatura',
            field=models.IntegerField(default=0, verbose_name='Zapoznanie z literatur'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_projekt',
            field=models.IntegerField(default=0, verbose_name='Przygotowanie projektu'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_przygotowanie_cw',
            field=models.IntegerField(default=0, verbose_name='Przygotowanie do wicze'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_sprawozdania',
            field=models.IntegerField(default=0, verbose_name='Sprawozdania'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='pw_wyklad',
            field=models.IntegerField(default=0, verbose_name='Przygotowanie do zaliczenia wykadu'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='wymagania_obecnosci',
            field=models.TextField(default='Obecno obowizkowa...', verbose_name='Wymagania obecnoci'),
        ),
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='zasady_oceniania',
            field=models.TextField(default='Zgodnie z regulaminem...', verbose_name='Sposoby ustalenia oceny kocowej'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='typ',
            field=models.CharField(choices=[('Obowizkowy', 'Obowizkowy'), ('Wybieralny', 'Wybieralny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modul',
            name='wymagane_ects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='formy_oceny',
            field=models.TextField(verbose_name='Metody weryfikacji wiedzy'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='literatura',
            field=models.TextField(verbose_name='Literatura'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='metody_nauczania',
            field=models.TextField(verbose_name='Metody nauczania'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='opis_wstepny',
            field=models.TextField(verbose_name='Cele ksztacenia'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_wstepne',
            field=models.TextField(verbose_name='Wymagania wstpne'),
        ),
    ]
