# Generated by Django 6.0.2 on 2026-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_szczegolysylabusa_efekty_tekstowe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efektuczenia',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejętności'), ('K', 'Kompetencje')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='poziom',
            field=models.CharField(choices=[('1', 'Pierwszy stopień'), ('2', 'Drugi stopień')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='wydzial',
            field=models.CharField(default='Wydział Informatyki', max_length=200),
        ),
        migrations.AlterField(
            model_name='modul',
            name='typ',
            field=models.CharField(choices=[('Obowiązkowy', 'Obowiązkowy'), ('Wybieralny', 'Wybieralny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='badania_naukowe',
            field=models.BooleanField(default=False, verbose_name='Związany z badaniami?'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='badania_publikacje',
            field=models.TextField(blank=True, default='', verbose_name='Badania i publikacje'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_kompetencje',
            field=models.TextField(blank=True, default='-', verbose_name='Efekty - Kompetencje'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_umiejetnosci',
            field=models.TextField(blank=True, default='-', verbose_name='Efekty - Umiejętności'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_wiedza',
            field=models.TextField(blank=True, default='-', verbose_name='Efekty - Wiedza'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='formy_oceny',
            field=models.TextField(blank=True, default='', verbose_name='Metody weryfikacji wiedzy'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='inne_informacje',
            field=models.TextField(blank=True, default='', verbose_name='Inne informacje'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='literatura',
            field=models.TextField(blank=True, default='', verbose_name='Literatura'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='metody_nauczania',
            field=models.TextField(blank=True, default='', verbose_name='Metody nauczania'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='odrabianie_zajec',
            field=models.TextField(blank=True, default='Konsultacja z prowadzącym...', verbose_name='Sposoby odrabiania'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='opis_wstepny',
            field=models.TextField(blank=True, default='', verbose_name='Cele kształcenia'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_egzamin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_literatura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_projekt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_przygotowanie_cw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_sprawozdania',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='pw_wyklad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_obecnosci',
            field=models.TextField(blank=True, default='Obecność obowiązkowa...', verbose_name='Wymagania obecności'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_wstepne',
            field=models.TextField(blank=True, default='', verbose_name='Wymagania wstępne'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='zasady_oceniania',
            field=models.TextField(blank=True, default='Zgodnie z regulaminem...', verbose_name='Sposoby ustalenia oceny'),
        ),
    ]
