# Generated by Django 6.0.2 on 2026-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_efektuczenia_kategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektów (mapowanie)'),
        ),
    ]
