# Generated by Django 6.0.2 on 2026-02-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_szczegolysylabusa_mapowanie_efektow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfektKierunkowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod efektu (np. K_W01)')),
                ('opis', models.TextField(verbose_name='Tre efektu')),
                ('kategoria', models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejtnoci'), ('K', 'Kompetencje')], default='W', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='efektuczenia',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejtnoci'), ('K', 'Kompetencje')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='poziom',
            field=models.CharField(choices=[('1', 'Pierwszy stopie'), ('2', 'Drugi stopie')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='wydzial',
            field=models.CharField(default='Wydzia Informatyki', max_length=200),
        ),
        migrations.AlterField(
            model_name='modul',
            name='typ',
            field=models.CharField(choices=[('Obowizkowy', 'Obowizkowy'), ('Wybieralny', 'Wybieralny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='badania_naukowe',
            field=models.BooleanField(default=False, verbose_name='Zwizany z badaniami?'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_umiejetnosci',
            field=models.TextField(blank=True, default='-', verbose_name='Efekty - Umiejtnoci'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektów (tekst)'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='odrabianie_zajec',
            field=models.TextField(blank=True, default='Konsultacja z prowadzcym...', verbose_name='Sposoby odrabiania'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='opis_wstepny',
            field=models.TextField(blank=True, default='', verbose_name='Cele ksztacenia'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_obecnosci',
            field=models.TextField(blank=True, default='Obecno obowizkowa...', verbose_name='Wymagania obecnoci'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_wstepne',
            field=models.TextField(blank=True, default='', verbose_name='Wymagania wstpne'),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='efekty_kierunkowe',
            field=models.ManyToManyField(blank=True, to='core.efektkierunkowy', verbose_name='Realizowane efekty kierunkowe'),
        ),
    ]
