# Generated by Django 6.0.2 on 2026-02-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_efektkierunkowy_alter_efektuczenia_kategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektÃ³w (tekst)'),
        ),
        migrations.CreateModel(
            name='EfektPrzedmiotowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejtnoci'), ('K', 'Kompetencje')], max_length=1)),
                ('kod_efektu_przedmiotowego', models.CharField(max_length=10, verbose_name='Kod (np. EU1)')),
                ('opis', models.TextField()),
                ('powiazany_efekt_kierunkowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.efektkierunkowy')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efekty_przedmiotowe', to='core.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='Wykladowca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(default='dr inÅ¼.', max_length=50, verbose_name='TytuÅ‚/StopieÅ„ naukowy')),
                ('katedra', models.CharField(max_length=100, verbose_name='Katedra/WydziaÅ‚')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='koordynatorzy',
            field=models.ManyToManyField(blank=True, related_name='przypisane_przedmioty', to='core.wykladowca'),
        ),
    ]
