# Generated by Django 6.0.2 on 2026-02-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_szczegolysylabusa_mapowanie_efektow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmiot',
            name='efekty_kierunkowe',
        ),
        migrations.AddField(
            model_name='efektkierunkowy',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moje_efekty', to='core.przedmiot'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektÃƒÂ³w (tekst)'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='katedra',
            field=models.CharField(max_length=100, verbose_name='Katedra/WydziaÃ…â€š'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr inÃ…Â¼.', max_length=50, verbose_name='TytuÃ…â€š/StopieÃ…â€ž naukowy'),
        ),
    ]
