# Generated by Django 6.0.2 on 2026-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_przedmiot_efekty_kierunkowe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektÃƒÆ’Ã‚Â³w (tekst)'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='katedra',
            field=models.CharField(max_length=100, verbose_name='Katedra/WydziaÃƒâ€¦Ã¢â‚¬Å¡'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr inÃƒâ€¦Ã‚Â¼.', max_length=50, verbose_name='TytuÃƒâ€¦Ã¢â‚¬Å¡/StopieÃƒâ€¦Ã¢â‚¬Å¾ naukowy'),
        ),
    ]
