# Generated by Django 6.0.2 on 2026-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_szczegolysylabusa_mapowanie_efektow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efektkierunkowy',
            name='przedmiot',
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='efekty_kierunkowe',
            field=models.ManyToManyField(blank=True, to='core.efektkierunkowy', verbose_name='Realizowane efekty kierunkowe'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â³w (tekst)'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='katedra',
            field=models.CharField(max_length=100, verbose_name='Katedra/WydziaÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr inÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¼.', max_length=50, verbose_name='TytuÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡/StopieÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾ naukowy'),
        ),
    ]
