# Generated by Django 6.0.2 on 2026-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_efektkierunkowy_przedmiot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmiot',
            name='efekty',
        ),
        migrations.RemoveField(
            model_name='przedmiot',
            name='opiekun',
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default='', verbose_name='Relacje efektów (tekst)'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='katedra',
            field=models.CharField(max_length=100, verbose_name='Katedra/Wydzia'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr in.', max_length=50, verbose_name='Tytu/Stopie naukowy'),
        ),
    ]
