# Generated by Django 6.0.2 on 2026-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_przedmiot_efekty_remove_przedmiot_opiekun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='kod',
            field=models.CharField(max_length=20, verbose_name='Kod efektu (np. K_W01)'),
        ),
        migrations.AlterField(
            model_name='efektuczenia',
            name='kod',
            field=models.CharField(max_length=20),
        ),
    ]
