# Generated by Django 6.0.2 on 2026-02-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_efektkierunkowy_kod_alter_efektuczenia_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szczegolysylabusa',
            name='badania_publikacje',
        ),
        migrations.AddField(
            model_name='kierunekstudiow',
            name='koordynator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koordynowane_kierunki', to='core.wykladowca'),
        ),
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiej?tno?ci'), ('K', 'Kompetencje')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='kod',
            field=models.CharField(max_length=20, verbose_name='Kod efektu'),
        ),
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='opis',
            field=models.TextField(verbose_name='Tre?? efektu'),
        ),
        migrations.AlterField(
            model_name='efektuczenia',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiej?tno?ci'), ('K', 'Kompetencje')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='poziom',
            field=models.CharField(choices=[('1', 'Pierwszy stopie?'), ('2', 'Drugi stopie?')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='wydzial',
            field=models.CharField(default='Wydzia? Informatyki', max_length=200),
        ),
        migrations.AlterField(
            model_name='modul',
            name='typ',
            field=models.CharField(choices=[('Obowi?zkowy', 'Obowi?zkowy'), ('Wybieralny', 'Wybieralny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='badania_naukowe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='efekty_kierunkowe',
            field=models.ManyToManyField(blank=True, to='core.efektkierunkowy'),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='godz_egzamin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_kompetencje',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_umiejetnosci',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='efekty_wiedza',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='formy_oceny',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='inne_informacje',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='literatura',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='mapowanie_efektow',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='metody_nauczania',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='odrabianie_zajec',
            field=models.TextField(blank=True, default='Konsultacja z prowadz?cym...'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='opis_wstepny',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_obecnosci',
            field=models.TextField(blank=True, default='Obecno?? obowi?zkowa...'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_wstepne',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='zasady_oceniania',
            field=models.TextField(blank=True, default='Zgodnie z regulaminem...'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='katedra',
            field=models.CharField(max_length=100, verbose_name='Katedra'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr in?.', max_length=50, verbose_name='Tytu?'),
        ),
        migrations.DeleteModel(
            name='EfektPrzedmiotowy',
        ),
    ]
