# Generated by Django 6.0.2 on 2026-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_szczegolysylabusa_badania_publikacje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='przedmiot',
            name='uwagi_statusu',
            field=models.TextField(blank=True, default='', verbose_name='Uwagi do sylabusa'),
        ),
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejętności'), ('K', 'Kompetencje')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='efektkierunkowy',
            name='opis',
            field=models.TextField(verbose_name='Treść efektu'),
        ),
        migrations.AlterField(
            model_name='efektuczenia',
            name='kategoria',
            field=models.CharField(choices=[('W', 'Wiedza'), ('U', 'Umiejętności'), ('K', 'Kompetencje')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='poziom',
            field=models.CharField(choices=[('1', 'Pierwszy stopień'), ('2', 'Drugi stopień')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='wydzial',
            field=models.CharField(default='Wydział Informatyki', max_length=200),
        ),
        migrations.AlterField(
            model_name='modul',
            name='typ',
            field=models.CharField(choices=[('Obowiązkowy', 'Obowiązkowy'), ('Wybieralny', 'Wybieralny')], max_length=20),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='status',
            field=models.CharField(choices=[('ROBOCZY', 'W edycji (Wykładowca)'), ('DO_POPRAWY', 'Do poprawy (Odrzucony)'), ('SPRAWDZONY', 'Sprawdzony (Koordynator Kierunku)'), ('ZATWIERDZONY', 'Zatwierdzony (Prodziekan)')], default='ROBOCZY', max_length=20),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='odrabianie_zajec',
            field=models.TextField(blank=True, default='Konsultacja z prowadzącym...'),
        ),
        migrations.AlterField(
            model_name='szczegolysylabusa',
            name='wymagania_obecnosci',
            field=models.TextField(blank=True, default='Obecność obowiązkowa...'),
        ),
        migrations.AlterField(
            model_name='wykladowca',
            name='tytul',
            field=models.CharField(default='dr inż.', max_length=50, verbose_name='Tytuł'),
        ),
    ]
