# Generated by Django 6.0.2 on 2026-04-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_przedmiot_uwagi_statusu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='status',
            field=models.CharField(choices=[('ROBOCZY', 'W edycji (Wykładowca)'), ('WERYFIKACJA', 'Do sprawdzenia (Szef Kierunku)'), ('DO_POPRAWY', 'Do poprawy (Odrzucony)'), ('SPRAWDZONY', 'Sprawdzony (Koordynator Kierunku)'), ('ZATWIERDZONY', 'Zatwierdzony (Prodziekan)')], default='ROBOCZY', max_length=20),
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='core.przedmiot')),
            ],
        ),
    ]
