# Generated by Django 6.0.2 on 2026-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_przedmiot_status_komentarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='status',
            field=models.CharField(choices=[('ROBOCZY', 'W edycji (Wykładowca)'), ('WERYFIKACJA', 'Do sprawdzenia (Koordynator Kierunku)'), ('DO_POPRAWY', 'Do poprawy (Odrzucony)'), ('SPRAWDZONY', 'Sprawdzony (Koordynator Kierunku)'), ('ZATWIERDZONY', 'Zatwierdzony (Prodziekan)')], default='ROBOCZY', max_length=20),
        ),
    ]
